apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-db
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      name: migrate-db
      labels:
        {{- include "chart.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migrate-db
          {{- include "chart.imageAndResources" (dict "root" .Values "ctx" .) | nindent 10 }}
          envFrom:
            - configMapRef:
                name: common
            - configMapRef:
                name: database
            - secretRef:
                name: secret
          command: [ "alembic", "upgrade", "head" ]
