.build:
  stage: build
  image:
    name: moby/buildkit:latest
    entrypoint: [""]
  variables:
    DOCKER_CONFIG: /docker
  script:
    - buildctl-daemonless.sh build
      --frontend dockerfile.v0
      --local context=$CI_PROJECT_DIR
      --local dockerfile=$CI_PROJECT_DIR
      --opt target=$TARGET
      --output type=image,name=$DOCKER_REGISTRY/$DOCKER_IMAGE-$TARGET:$CI_COMMIT_SHORT_SHA,push=true

build-dev:
  extends: .build
  variables:
    TARGET: dev

#build-prod:
#  extends: .build
#  variables:
#    TARGET: prod
#  only:
#    refs:
#      - master
