name: CI (master)

on:
  pull_request:
    branches:
      - master
    types:
      - closed
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy
        required: true
        default: stage
        type: choice
        options:
          - stage
          - prod

concurrency:
  group: master-${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'stage' }}
  cancel-in-progress: false

jobs:
  pipeline:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/pipeline.yaml
    with:
      environment: ${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'stage' }}
      deploy: ${{ github.event_name == 'workflow_dispatch' }}
    secrets: inherit
